<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Reservation_Control.aspx.cs" Inherits="Restaurant.Reservation_Control" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
     <title>International Restaurant</title>

    <!--Linking the css and bootstrap stylesheet-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link href="css/reservation_control.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
    <!--Main Wrapper-->
    <div class="main-wrapper">
        <div class="user-logout">
                <h5 style="font-size: 12px; color: black;"><%=Session["log"]%></h5>
                <h6 style="color: lightseagreen"> <%=Session["uname"]%><%=Session["adname"]%><%=Session["empname"] %></h6>
                <asp:Button ID="Button2" runat="server" Visible="False" Text="Logout" OnClick="Button2_Click" cssClass="btn btn-amber btn-lg"/>
            </div>
        
            <!--Form Layout-->
            <div class="form-layout">
                <h3><u>Reservation Status</u></h3>
                <!--Texts and Textboxes-->
                    
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" DataKeyNames="ID"
                            DataSourceID="SqlDataSource1" EnableModelValidation="True" 
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                            <Columns>
                                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="false" ReadOnly="true" SortExpression="ID"/>
                                <asp:BoundField DataField="FirstName" HeaderText ="First Name" SortExpression="FirstName" />
                                <asp:BoundField DataField="LastName" HeaderText ="Las Name" SortExpression="LastName" />
                                <asp:BoundField DataField="phone_number" HeaderText ="Phone Number" SortExpression="phone_number" />
                                <asp:BoundField DataField="email_address" HeaderText ="Email Address" SortExpression="email_address" />
                                <asp:BoundField DataField="people_num" HeaderText ="People" SortExpression="people_num" />
                                <asp:BoundField DataField="selected_table" HeaderText ="Table" SortExpression="selected_table" />
                                <asp:BoundField DataField="reservation_date" HeaderText ="Date" SortExpression="reservation_date" />
                                <asp:BoundField DataField="reservation_time" HeaderText ="Time" SortExpression="reservation_time" />
                                <asp:BoundField DataField="card_num" HeaderText ="Card" SortExpression="card_num" />
                            </Columns>
                        </asp:GridView>
        
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                            connectionString="Data Source=SANIL\MSSQLSERVER01;Initial Catalog=restaurant;Integrated Security=SSPI;Persist Security Info=False"
                            SelectCommand="SELECT * FROM reservation"
                            UpdateCommand="UPDATE reservation Set [FirstName]=@FirstName, [LastName]=@LastName, [phone_number]=@phone_number, [email_address]=@email_address, [people_num]=@people_num, [selected_table]=@selected_table, [reservation_date]=@reservation_date, [reservation_time]=@reservation_time, [card_num]=@card_num Where [ID]=@ID" 
                            DeleteCommand="DELETE from reservation Where [ID]=@ID" OnSelecting="SqlDataSource1_Selecting"></asp:SqlDataSource>
                    <br />
                <div class="back">
                    <h6 style="margin-left: 35rem;">Go back to <a href="admincontrol.aspx" style="color: lightseagreen;">Admin Control</a> page.</h6>
                </div>
                </div>
            </div>
        </form>
</body>
</html>
